modLoader="javafml"
loaderVersion="[40,)"
license="LGPL 2.1"

[[mods]]
modId="ntgl"
version="${file.jarVersion}"
displayName="NukaTeam Gun Lib"
updateJSONURL=""
displayURL=""
logoFile="logo.png"
authors="Dayton, Jetug"
credits = "MrCrayfish, AzureDoom"
description=""

[[dependencies.ntgl]]
modId="forge"
mandatory=true
versionRange="[40.2.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.ntgl]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
[[dependencies.ntgl]]
modId="framework"
mandatory=true
versionRange="[0.4.2,)"
ordering="NONE"
side="BOTH"
[[dependencies.ntgl]]
modId="azurelib"
mandatory=true
versionRange="[1.0.23,)"
ordering="AFTER"
side="BOTH"

[modproperties.ntgl]
    catalogueImageIcon=""
